apiVersion: v1
kind: Service
metadata:
  name: {{ include "smackweb.fullname" . }}
  labels:
    app: {{ include "smackweb.fullname" . }}
    app.kubernetes.io/name: {{ include "smackweb.name" . }}
    helm.sh/chart: {{ include "smackweb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
  selector:
    app: {{ include "smackweb.fullname" . }}
    app.kubernetes.io/name: {{ include "smackweb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
