apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: smackweb-vs
spec:
  hosts:
  - "*"
  gateways:
  - smackweb-gateway
  http:
  - route:
    - destination:
        host: smackweb