apiVersion: v1
kind: Service
metadata:
  name: smackweb
  labels:
    app: smackweb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: smackweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smackweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smackweb
  template:
    metadata:
      labels:
        app: smackweb
    spec:
      containers:
      - name: smackweb
        image: pierluigi.azurecr.io/smackweb:master-d9f0e69d
        env:
        - name: API_SERVICE
          value: "smackapi.default.svc.cluster.local"
        - name: API_PORT
          value: "8081"
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: acrsecret
